[theme]
primaryColor = "#606c38"
backgroundColor = "#fefae0"
secondaryBackgroundColor = "#3d4a2d"
textColor = "#283618"
font = "sans serif"

[client]
showErrorDetails = true

[server]
headless = true
